### ISSUE TITLE
Portfolio Desktop version 1

### ISSUE THREAD

**Issue by dev-mamun** [dev-mamun/microverse-portfolio#13]

**Comment by ayaderaghul** [comment]
You have semantic HTML tags, which provides thoughtful information about the document, gives it structure and professionalism.

**Comment by ayaderaghul** [comment]
For the background in the contact section, you can download the layers from the figma template as svg file and merge them. I suggest to use softwares such as inkscape for Linux system.

**Comment by alphym** [comment]
if the background merge doesn't work consider this example 👍

  background-image: url(firefox.png), url(bubbles.png), linear-gradient(to right, rgba(30, 75, 115, 1), rgba(255, 255, 255, 0));
  background-repeat: no-repeat, no-repeat, no-repeat;
  background-position: bottom right, left, right;
}
